### ISSUE TITLE
Suggestion: Fully customizable controls

### ISSUE THREAD

**Issue by wickjames086** [skyfloogle/red-viper#14]
I think it would be an improvement to be able to completely remap the controls including the controls on the touch screen, preferably on a game by game basis. My ideal would be the Right D Pad mapped to the face buttons, A & B are mapped to ZL and ZR, and the touch screen simply pauses the emulator. But then for games that don't use the Right D Pad, A & B would just be mapped to A & B, hence the option for game-specific remaps.

**Comment by riggles1** [comment]
Another situation, while there is a rom patch for Mario Clash to swap A-B, it would be nice to set the ABXY in a configuration where A-X are AB and B-Y are BA so that people who haven't patched the game don't have to reassign it every time they want to play Mario Clash. None of the selectable ABXY layouts are set up like that.

**Comment by skyfloogle** [comment]
I was planning on implementing the inverted face button layout @riggles1 described, and allowing some customization for the triggers (L/R on both, A/B on either pair in either order). I think that should cover all reasonable use cases.
Game specific configs is a good idea, I've had a few comments about that.

**Comment by riggles1** [comment]
> I was planning on implementing the inverted face button layout @riggles1 described, and allowing some customization for the triggers (L/R on both, A/B on either pair in either order). I think that should cover all reasonable use cases (let me know if I'm wrong though). Game specific configs is a good idea, I've had a few comments about that.

Awesome! While on the topic of remaps, is it possible to set "toggle" variants for the shoulder button keys? (setting ZL/ZR for this for example)
Constantly holding L/R to dash in Wario Land or Mario Clash can get a bit tiring for the hands, since you want to hold those in at basically all times.

I'm pretty used to having my hands in weird positions, but I know a lot of people easily get hand cramps by the 3DS formfactor.

**Comment by cheatfreak47** [comment]
I think full remapping including hotkeys like fast forward and the future save states would be nice

**Comment by Mayonaka-7** [comment]
Circle Pad Pro support on o3DS models would be nice, as well.

**Comment by skyfloogle** [comment]
Recent commits added a custom control mode where any button can be remapped. Toggle and turbo modes are also supported.
