### ISSUE TITLE
Please support more buttons

### ISSUE THREAD

**Issue by Epic0522** [skyfloogle/red-viper#32]
The control in game Red Alarm is quite difficult. please add personalized button palette and allow use ZL ZR button🙏

**Comment by skyfloogle** [comment]
In the short term I'm planning on optionally allowing for mapping the A/B buttons to one set of triggers, while the other is still L/R. Does this sound like it matches your use case?

**Comment by Epic0522** [comment]
Circle pad for left dpad on the VB controller and 3ds dpad for right dpad is the best solution i think，apart from the Z buttons on New models

**Comment by ChrisHighwind** [comment]
Red Alarm actually has 4 button configs in-game, and the configs on the right side of the screen make it so the right d-pad can be used to adjust the speed of the ship and slide left and right. Try setting the in-game controls to one of those configs (the configs on the bottom invert the up/down flight controls) and have the emulator swap the right d-pad and A/B buttons so that the former are on the face buttons, as the speed/slide configs make it so A and B aren't used.

**Comment by vaguerant** [comment]
I have a very not-OK hacked together version I'm running locally that has configurable shoulder buttons. I won't bother PRing it because my code is pure spaghetti, but it basically adds a toggle to the controls screen that lets you swap the shoulder buttons like so:
<div align="center">

![2024-03-04_21-02-43 693_bot](https://github.com/skyfloogle/red-viper/assets/5259025/ed42b8bc-d19e-44ee-96e8-2ac7634def1c)

|  x  | L | ZL | ZR | R |
| :-: |:-:|:-: |:-: |:-:|
|**0**| L | B  | A  | R |
|**1**| L | A  | B  | R |
|**2**| B | L  | R  | A |
|**3**| A | L  | R  | B |
</div>
I think this covers every possible layout somebody could realistically want for the L/R/ZL/ZR buttons. The inverted A/B layouts (numbering from 0-3, that's 1 and 3) could probably be dropped but something roughly like this should do the job.

Obviously, I'll post my diff if it's wanted, but it would be better if implemented from scratch by somebody competent.

**Test build:**
[red-viper_v0.9.1_sliders-and-shoulders.zip](https://github.com/skyfloogle/red-viper/files/14480419/red-viper_v0.9.1_sliders-and-shoulders.zip)
Note, this build also contains a different slider configuration I was experimenting with during that discussion, don't mind that.

This also just assumes you're running a New 3DS, I don't advise running this build on models without a second set of shoulder buttons.

**Comment by Epic0522** [comment]
Thank for your work！
I think the second dpad’s left and right buttons should be mapped on the shoulders🤔

**Comment by skyfloogle** [comment]
@vaguerant's proposal is basically what I had in mind, except I was thinking of also mapping L and R to both pairs, but maybe that's not necessary.

**Comment by vaguerant** [comment]
> Thank for your work！ I think the second dpad’s left and right buttons should be mapped on the shoulders🤔

I guess this could be automated based on whether you have the buttons or D-pad on the touch screen. If you already have A/B on the face buttons, you don't really need A/B on the Z buttons as well. In theory it could be set up so that D-pad left/right are on whichever shoulder buttons are currently "spare" when you don't need them to be A/B. That way, there's no need for additional config options.

**Comment by pmsobrado** [comment]
@skyfloogle will you support using the right C-Stick of New 3DS?

**Comment by Epic0522** [comment]
> @skyfloogle will you support using the right C-Stick of New 3DS?

It already supported for the right dpad on the original VB controller

**Comment by pmsobrado** [comment]
> > @skyfloogle will you support using the right C-Stick of New 3DS?
> 
> It already supported for the right dpad on the original VB controller

Damn, didn't noticed it haha thanks!

**Comment by vaguerant** [comment]
> Or just map the left dpad on main stick and the right dpad on the 3ds’ dpad I think it is the best solution because the cstick is too hard to use

How many games would that really be useful in? For Jack Bros. and Red Alarm, you really need access to both D-pads at the same time (under different thumbs) to play properly. Having the Circle Pad and D-pad be the Virtual Boy D-pads would be extremely limiting because you only have one left thumb.

I was talking about my awful spaghetti code earlier and this is the kind of stuff I mean. Absolutely untenable.

```c
        C2D_DrawText(
            tVBOpt.ABLR_MODE <= 1 ? &text_L :
            !buttons_on_screen ? &text_RPAD_L : tVBOpt.ABLR_MODE == 2 ? &text_B : &text_A,
            C2D_AlignCenter | C2D_WithColor, SHOULDX - SHOULDW/2 + SHOULDH*0.75f, SHOULDY + SHOULDH/2 - 8, 0, 0.5, 0.5, C2D_Color32(255, 255, 255, 255));
        C2D_DrawText(
            tVBOpt.ABLR_MODE == 0 ? !buttons_on_screen ? &text_RPAD_L : &text_B :
            tVBOpt.ABLR_MODE == 1 ? !buttons_on_screen ? &text_RPAD_L : &text_A : &text_L,
            C2D_AlignCenter | C2D_WithColor, SHOULDX - SHOULDW/2 + SHOULDH*1.67f, SHOULDY + SHOULDH/2 - 8, 0, 0.5, 0.5, C2D_Color32(255, 255, 255, 255));
        C2D_DrawText(
            tVBOpt.ABLR_MODE == 0 ? !buttons_on_screen ? &text_RPAD_R : &text_A :
            tVBOpt.ABLR_MODE == 1 ? !buttons_on_screen ? &text_RPAD_R : &text_B : &text_R,
            C2D_AlignCenter | C2D_WithColor, SHOULDX - SHOULDW/2 + SHOULDW - SHOULDH*1.67f, SHOULDY + SHOULDH/2 - 8, 0, 0.5, 0.5, C2D_Color32(255, 255, 255, 255));
        C2D_DrawText(
            tVBOpt.ABLR_MODE <= 1 ? &text_R :
            !buttons_on_screen ? &text_RPAD_R : tVBOpt.ABLR_MODE == 2 ? &text_A : &text_B,
            C2D_AlignCenter | C2D_WithColor, SHOULDX - SHOULDW/2 + SHOULDW - SHOULDH*0.75f, SHOULDY + SHOULDH/2 - 8, 0, 0.5, 0.5, C2D_Color32(255, 255, 255, 255));
```

@skyfloogle If you do end up (optionally) putting the D-pad on ZL/ZR which is what that hideous mess above is doing, you might find the Unicode codepoints for various Nintendo buttons useful:
<div align="center">

![image](https://github.com/skyfloogle/red-viper/assets/5259025/af3a1c0d-d8cb-4e08-bf00-6b5ffc23bc7e)
</div>

These are grabbed from the Wii U system font, so things might be slightly different on 3DS, but at least `\uE07B` and `\uE07C` are the same, I was able to use them to put D-pad directions in the toggle:
<div align="center">

![2024-03-05_20-58-52 141_bot](https://github.com/skyfloogle/red-viper/assets/5259025/9ec96b3a-300e-45a8-8d0e-39739f8eee3c)
</div>

```c
    C2D_TextParse(&text_RPAD_L, static_textbuf, "\uE07B");
    C2D_TextOptimize(&text_RPAD_L);
    C2D_TextParse(&text_RPAD_R, static_textbuf, "\uE07C");
    C2D_TextOptimize(&text_RPAD_R);
```

**Test build:**
[red-viper_v0.9.1_this-monstrosity.zip](https://github.com/skyfloogle/red-viper/files/14494225/red-viper_v0.9.1_this-monstrosity.zip)
This is absolutely disgusting.

**Comment by vaguerant** [comment]
Re: The button glyphs, going all in actually looks kind of nice, I think. I don't know that I'd say better, but looks a bit more Nintendo-esque certainly.

<div align="center">

![2024-03-05_23-00-14 865_bot](https://github.com/skyfloogle/red-viper/assets/5259025/f696ceb0-1707-489c-8554-5b228882825b)
</div>

**Comment by Epic0522** [comment]
Woo that’s awesome!
this emulator made 3ds great again

**Comment by Epic0522** [comment]
> > Or just map the left dpad on main stick and the right dpad on the 3ds’ dpad I think it is the best solution because the cstick is too hard to use
> 
> How many games would that really be useful in? For Jack Bros. and Red Alarm, you really need access to both D-pads at the same time (under different thumbs) to play properly. Having the Circle Pad and D-pad be the Virtual Boy D-pads would be extremely limiting because you only have one left thumb.
> 
> I was talking about my awful spaghetti code earlier and this is the kind of stuff I mean. Absolutely untenable.
> 
> ```c
>         C2D_DrawText(
>             tVBOpt.ABLR_MODE <= 1 ? &text_L :
>             !buttons_on_screen ? &text_RPAD_L : tVBOpt.ABLR_MODE == 2 ? &text_B : &text_A,
>             C2D_AlignCenter | C2D_WithColor, SHOULDX - SHOULDW/2 + SHOULDH*0.75f, SHOULDY + SHOULDH/2 - 8, 0, 0.5, 0.5, C2D_Color32(255, 255, 255, 255));
>         C2D_DrawText(
>             tVBOpt.ABLR_MODE == 0 ? !buttons_on_screen ? &text_RPAD_L : &text_B :
>             tVBOpt.ABLR_MODE == 1 ? !buttons_on_screen ? &text_RPAD_L : &text_A : &text_L,
>             C2D_AlignCenter | C2D_WithColor, SHOULDX - SHOULDW/2 + SHOULDH*1.67f, SHOULDY + SHOULDH/2 - 8, 0, 0.5, 0.5, C2D_Color32(255, 255, 255, 255));
>         C2D_DrawText(
>             tVBOpt.ABLR_MODE == 0 ? !buttons_on_screen ? &text_RPAD_R : &text_A :
>             tVBOpt.ABLR_MODE == 1 ? !buttons_on_screen ? &text_RPAD_R : &text_B : &text_R,
>             C2D_AlignCenter | C2D_WithColor, SHOULDX - SHOULDW/2 + SHOULDW - SHOULDH*1.67f, SHOULDY + SHOULDH/2 - 8, 0, 0.5, 0.5, C2D_Color32(255, 255, 255, 255));
>         C2D_DrawText(
>             tVBOpt.ABLR_MODE <= 1 ? &text_R :
>             !buttons_on_screen ? &text_RPAD_R : tVBOpt.ABLR_MODE == 2 ? &text_A : &text_B,
>             C2D_AlignCenter | C2D_WithColor, SHOULDX - SHOULDW/2 + SHOULDW - SHOULDH*0.75f, SHOULDY + SHOULDH/2 - 8, 0, 0.5, 0.5, C2D_Color32(255, 255, 255, 255));
> ```
> 
> @skyfloogle If you do end up (optionally) putting the D-pad on ZL/ZR which is what that hideous mess above is doing, you might find the Unicode codepoints for various Nintendo buttons useful:
> 
> ![image](https://private-user-images.githubusercontent.com/5259025/310150454-13792781-46be-49af-922c-28bf7aef1070.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTA1MjEsIm5iZiI6MTcwOTY1MDIyMSwicGF0aCI6Ii81MjU5MDI1LzMxMDE1MDQ1NC0xMzc5Mjc4MS00NmJlLTQ5YWYtOTIyYy0yOGJmN2FlZjEwNzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTQ1MDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlmY2U4OGM0YWY3MWUzMmU1MTgxNDk3MTBlNWFiMWE4NTI3ZGViMzFjODYyN2YzZjNkYWE5MTI4NWQ4MTA5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GqNIvaXERpIQczh5V8gTcr3nP1sAq50-Hmnh0CP8cxc)
> 
> e.g. I was able to use `\uE07B` and `\uE07C` to put D-pad directions in the toggle:
> 
> ![2024-03-05_20-58-52 141_bot](https://private-user-images.githubusercontent.com/5259025/310089780-9ec96b3a-300e-45a8-8d0e-39739f8eee3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTA1MjEsIm5iZiI6MTcwOTY1MDIyMSwicGF0aCI6Ii81MjU5MDI1LzMxMDA4OTc4MC05ZWM5NmIzYS0zMDBlLTQ1YTgtOGQwZS0zOTczOWY4ZWVlM2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMTQ1MDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTg3NjEwMmZhMjA4ZTc0MzFlZWY1ZjVlZmQzMmJlNGQ4YTEzMzRjNmEzMGU5ZDk4Nzc5MTliMzhhMjlkNWFiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.imye0VRtV-KHXeKsPa8Y1Qn_atzakBKlWqsRsT5IEag)
> 
> ```c
>     C2D_TextParse(&text_RPAD_L, static_textbuf, "\uE07B");
>     C2D_TextOptimize(&text_RPAD_L);
>     C2D_TextParse(&text_RPAD_R, static_textbuf, "\uE07C");
>     C2D_TextOptimize(&text_RPAD_R);
> ```
> 
> **Test build:** [red-viper_v0.9.1_this-monstrosity_hotfix.zip](https://github.com/skyfloogle/red-viper/files/14494398/red-viper_v0.9.1_this-monstrosity_hotfix.zip) This is absolutely disgusting.

it’s true that controlling two dpad is hectic ，but using that stupid cstick is more unbearable

**Comment by skyfloogle** [comment]
I'm pretty sure this use case is covered by putting the D-Pad on the face buttons using the "switch" button in the top right.

**Comment by vaguerant** [comment]
I'm working on cleaning up my shoulder button stuff, so if you haven't already got it going on your end I will throw a PR your way once that's done. I still have no idea what I'm doing, so no hard feelings if you're already working on it or just prefer to reject and do it properly.
