### ISSUE TITLE
Crash when launching VB Wario Land

### ISSUE THREAD

**Issue by FulguroBoy** [skyfloogle/red-viper#52]
When booting Wario Land, the application crashes everytime. I have not tested with other games yet. I'm on an O3DS, with the latest stable version (2024-03-24).
Here's the dump file:
[crash_dump_00000000.dmp](https://github.com/skyfloogle/red-viper/files/14738501/crash_dump_00000000.dmp)

EDIT: this only happens on the .cia version of the emulator, the .3dsx boots the game just fine

**Comment by redunka-zver** [comment]
Same here: O3DS, every single game crashes on the .cia version.
Apparently, the first build to start having this problem is the one that [adds improved debug info dumping](https://github.com/skyfloogle/red-viper/actions/runs/8334202065).
In fact, you don't even need to launch any games to get a crash, as the same happens after tapping that new "Save debug info" button in the Options menu, and it looks like even the .3dsx version can be crashed that way ([the dump, just in case](https://github.com/skyfloogle/red-viper/files/14744414/crash_dump_00000009.dmp)), but not as consistently as the .cia one.

**Comment by skyfloogle** [comment]
Seems like less RAM is available on the cia than on the 3dsx, and I didn't test the cia. Oops!
