### ISSUE TITLE
Golf color issues

### ISSUE THREAD

**Issue by HexaBlade007** [skyfloogle/red-viper#8]
On some occasion when pressing the "shot" button while playing golf, the entire field turns black, goes back to color when I exit out the option. Not sure if this is part of the game or from the emulator. Using Old 2DS

**Comment by gingerbeardman** [comment]
Not specific to golf but it's noticable how different the reds are in the emulator compared to The Real Thing™

**Comment by DuplexEagle** [comment]
> Not specific to Golf but it's noticeable how different the reds are in the emulator compared to The Real Thing™

I didn't know that. Is that an issue with the emulator or an inherent issue with the 3DS display not being able to display the same exact shade or brightness of red?

**Comment by riggles1** [comment]
The 3DS panels themselves, the intensity of the red isn't there and looks dull. Especially compared to what OLED is capable of. It's very mellow, combined with other colors it's good enough and relatively to other colors your brain starts to just see it as more intense than it is. But when red is by itself it looks lacking. 

Setting the color to a more pinkish red is what I do, since magenta is better saturated or color intense on there.

**Comment by gingerbeardman** [comment]
> > Not specific to Golf but it's noticeable how different the reds are in the emulator compared to The Real Thing™
> 
> I didn't know that. Is that an issue with the emulator or an inherent issue with the 3DS display not being able to display the same exact shade or brightness of red?

Yeah, I think it's both.

**Comment by skyfloogle** [comment]
The Golf playfield turning black seems to have fixed itself at some point. Given that that was the original purpose of this issue, I'll close it, leaving #55 for the colour accuracy issues.
